# Generated by Django 5.1 on 2024-08-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('BenAndJerrys', "Ben & Jerry's"), ('Magnum', 'Magnum'), ('DairyQueen', 'Dairy Queen')], default='Magnum', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IceCream', 'Ice Cream'), ('Gelato', 'Gelato'), ('IceCreamBars', 'Ice Cream Bars')], default='Ice Cream', max_length=50),
        ),
    ]
