# Generated by Django 4.2.15 on 2024-08-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_enquiry_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Enquiries'},
        ),
    ]
