# Generated by Django 4.2.15 on 2024-09-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
